name = "yung-munny-smp"
author = "Shadowevil015 & Flat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bfef6ec142c7ad52c255a2743b12bd5d26c4444a835bbbbf382114fe00cc302e"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
