name = "yung-munny-smp"
author = "Shadowevil015 & Flat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "942264bf318ee5a3748d6a42601518a6fb98fb68ff335c337235eabbc3dcd92c"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
