name = "flat-smp"
author = "Shadowevil015 & Flat"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f85d4dd61b476c20e28b6c58f7d97fe42fb35dbbfe60ff8b459ba5202e53324"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
