name = "flat-smp"
author = "Shadowevil015 & Flat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aad8875b5b2da40a0ea42fcb6c966a58d5c54dbfc7a2a8afbdc5ea409b74a717"

[versions]
minecraft = "1.18.2"
quilt = "0.17.1-beta.4"
