name = "flat-smp"
author = "Shadowevil015 & Flat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8316e5963ce219abb8baebcdccd632d16517ac3e9e3bbbc014b9322e4114c50"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
