name = "flat-smp"
author = "Shadowevil015 & Flat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df8ebe15f70f044d48f8f0ed0caffea5724b2b9cffadb603fb532fe68abee932"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
