name = "yung-munny-smp"
author = "Shadowevil015 & Flat"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee9aec52d17c2a65652ff70bdea6886221f9fc549c1603d92a40b466cf118a4b"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
