name = "yung-munny-smp"
author = "Shadowevil015 & Flat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca6b086387d100b35d5b85b3c5e1f8a490ef33d697d2cfbcb70a78f8e07a0345"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
