name = "yung-munny-smp"
author = "Shadowevil015 & Flat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "034efcce9a0217f88da757252ef16fa52e0fdef3dcc362027dd01483e44a2570"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
