name = "yung-munny-smp"
author = "Shadowevil015 & Flat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed6ef2aaa50054e56f8a9109a9e3b8de8741e68f48455415218d80b3ed6a8953"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
