name = "flat-smp"
author = "Shadowevil015 & Flat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3fb3aa15a324a4977d28490d19ec590bcaa6989a358b2ecef4e17c65dfd6003e"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
